version: '3'

services:
  web:
    image: windy007008/web_yt_scraper:latest
    restart: always
    ports:
      - "5002:5002"
    env_file:  # 添加这行
      - .env   # 指定.env文件
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-your-secret-key}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_ENV=development  # 标记为开发环境
      - HTTP_PROXY=http://host.docker.internal:10809
      - HTTPS_PROXY=http://host.docker.internal:10809
      - http_proxy=http://host.docker.internal:10809
      - https_proxy=http://host.docker.internal:10809


    volumes:
      - ./instance:/app/instance:rw
      - ./logs:/app/logs:rw  # 新增日志卷挂载
      - /etc/letsencrypt/live/windy.run/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/windy.run/privkey.pem:/etc/ssl/certs/privkey.pem:ro
    user: "1000:1000"  # 使用宿主机的UID:GID
    command: [
              "gunicorn", 
              "--workers", "4",
              "--timeout", "120",
              "--keep-alive", "5",
              "--max-requests", "1000",
              "--max-requests-jitter", "50",
              "--log-level", "debug",        # 改为 error/debug 级别
              "--access-logfile", "-",
              "--error-logfile", "-",
                # "--certfile", "/etc/ssl/certs/fullchain.pem",  # 添加 SSL 证书配置

                # "--keyfile", "/etc/ssl/certs/privkey.pem",     # 添加 SSL 密钥配置
              "--bind", "0.0.0.0:5002",
              "--access-logformat", "%(h)s %(l)s %(u)s %(t)s '%(r)s' %(s)s %(b)s '%(f)s' '%(a)s'",  # 添加自定义日志格式
                "app:app"
              # "python", "app.py"
              ]

volumes:
  instance:


